ckpt_path: /home/nas4_user/taewoongkang/repos/2d/AnimateDiff/checkpoints/dreamshaperXL_alpha2Xl10.safetensors
motion_module_path: /home/nas4_user/taewoongkang/repos/2d/AnimateDiff/models/Motion_Module/mm_sdxl_v10_beta.ckpt

seed:           -1

guidance_scale: 10
steps: 100

prompt:
  - "portrait of a man, fireworks, 8k uhd, high quality, road, sunset, motion blur, depth blur, cinematic, filmic image 4k, 8k. Natural sunlight, vibrant color, reflections" 
  - "night view, sea beach landscape, with a lighthouse, trending on artstation, by Noah Bradley, highly detailed, high quality, 4k HDR, path tracking, calm landscape, high consistency, soft lighting, <lora:xl_more_art-full_v1:0.3> in Serene grids, transcendent fields, quiet repetitions, sublime reduction in Brooding landscapes, epic scale, German myth, layered symbolic density"
  
n_prompt:
  - "embedding:BadDream, embedding:UnrealisticDream"
  - "(worst quality), (low quality), (normal quality), lowres, blurry, hand, signature, normal quality"
  