motion_module_path: /home/nas4_user/taewoongkang/repos/2d/AnimateDiff/models/Motion_Module/mm_sdxl_v10_beta.ckpt

seed:           -1

guidance_scale: 8.5
steps: 100

prompt:
  - "close up Portrait photo of muscular bearded guy in a worn mech suit, 4k, high resolution.Realistic, Cinematic, high resolution"
  - "Jane Eyre with headphones, natural skin texture,4mm,k textures, soft cinematic light, adobe lightroom, photolab,"
  # - "A disoriented astronaut, lost in a galaxy of swirling colors, floating in zero gravity, grasping at memories, poignant loneliness, stunning realism, cosmic chaos, emotional depth, 12K, hyperrealism, unforgettable, mixed media, celestial, dark, introspective"

n_prompt:
  - ""
  - ""